# Generated by Django 5.2.8 on 2026-03-10 18:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NameRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Placeholder name region', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_turn', models.IntegerField(default=0)),
                ('budget', models.IntegerField(default=100)),
                ('citizen_satisfaction', models.IntegerField(default=50)),
                ('environment', models.IntegerField(default=50)),
                ('military', models.IntegerField(default=50)),
                ('is_active', models.BooleanField(default=True)),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProblemInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Placeholder problem', max_length=100)),
                ('description', models.TextField(default='Placeholder problem description')),
                ('time_before_expiration', models.IntegerField(default=0)),
                ('max_budget_to_appear', models.IntegerField(default=1000)),
                ('max_citizen_satisfaction_to_appear', models.IntegerField(default=1000)),
                ('max_environment_to_appear', models.IntegerField(default=1000)),
                ('max_military_to_appear', models.IntegerField(default=1000)),
                ('min_budget_to_appear', models.IntegerField(default=0)),
                ('min_citizen_satisfaction_to_appear', models.IntegerField(default=0)),
                ('min_environment_to_appear', models.IntegerField(default=0)),
                ('min_military_to_appear', models.IntegerField(default=0)),
                ('budget_bias', models.IntegerField(default=1)),
                ('citizen_satisfaction_bias', models.IntegerField(default=1)),
                ('environment_bias', models.IntegerField(default=1)),
                ('military_bias', models.IntegerField(default=1)),
                ('ideal_budget', models.IntegerField(default=500)),
                ('ideal_citizen_satisfaction', models.IntegerField(default=500)),
                ('ideal_environment', models.IntegerField(default=500)),
                ('ideal_military', models.IntegerField(default=500)),
                ('possible_regions', models.ManyToManyField(related_name='possible_problems', to='main.nameregion')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Placeholder region', max_length=100)),
                ('occupied', models.BooleanField(default=False)),
                ('game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='main.game')),
                ('problem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regions', to='main.probleminstance')),
            ],
        ),
        migrations.CreateModel(
            name='SolutionChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Placeholder solution', max_length=100)),
                ('description', models.CharField(default='Placeholder solution', max_length=255)),
                ('time_before_effect', models.IntegerField(default=0)),
                ('budget_change', models.IntegerField(default=0)),
                ('citizen_satisfaction_change', models.IntegerField(default=0)),
                ('environment_change', models.IntegerField(default=0)),
                ('military_change', models.IntegerField(default=0)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solutions', to='main.probleminstance')),
            ],
        ),
    ]
