# Generated by Django 5.2.8 on 2026-04-28 19:44

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='NameRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Placeholder name region', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GameUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_turn', models.IntegerField(default=0)),
                ('economy', models.IntegerField(default=100)),
                ('citizen_satisfaction', models.IntegerField(default=50)),
                ('environment', models.IntegerField(default=50)),
                ('military_power', models.IntegerField(default=50)),
                ('is_active', models.BooleanField(default=True)),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProblemInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Placeholder problem', max_length=100)),
                ('description', models.TextField(default='Placeholder problem description')),
                ('time_before_expiration', models.IntegerField(default=0)),
                ('rarity', models.IntegerField(default=1)),
                ('max_budget_to_appear', models.IntegerField(default=1000)),
                ('max_citizen_satisfaction_to_appear', models.IntegerField(default=1000)),
                ('max_environment_to_appear', models.IntegerField(default=1000)),
                ('max_military_to_appear', models.IntegerField(default=1000)),
                ('min_budget_to_appear', models.IntegerField(default=0)),
                ('min_citizen_satisfaction_to_appear', models.IntegerField(default=0)),
                ('min_environment_to_appear', models.IntegerField(default=0)),
                ('min_military_to_appear', models.IntegerField(default=0)),
                ('budget_bias', models.FloatField(default=1)),
                ('citizen_satisfaction_bias', models.FloatField(default=1)),
                ('environment_bias', models.FloatField(default=1)),
                ('military_bias', models.FloatField(default=1)),
                ('budget_tendency', models.IntegerField(choices=[(0, 'Downward'), (1, 'Upward')], default=0)),
                ('citizen_satisfaction_tendency', models.IntegerField(choices=[(0, 'Downward'), (1, 'Upward')], default=0)),
                ('environment_tendency', models.IntegerField(choices=[(0, 'Downward'), (1, 'Upward')], default=0)),
                ('military_tendency', models.IntegerField(choices=[(0, 'Downward'), (1, 'Upward')], default=0)),
                ('possible_regions', models.ManyToManyField(related_name='possible_problems', to='main.nameregion')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Placeholder region', max_length=100)),
                ('occupied', models.BooleanField(default=False)),
                ('game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='main.game')),
                ('problem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regions', to='main.probleminstance')),
            ],
        ),
        migrations.CreateModel(
            name='SolutionChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Placeholder solution', max_length=100)),
                ('description', models.CharField(default='Placeholder solution', max_length=255)),
                ('time_before_effect', models.IntegerField(default=0)),
                ('budget_change', models.IntegerField(default=0)),
                ('citizen_satisfaction_change', models.IntegerField(default=0)),
                ('environment_change', models.IntegerField(default=0)),
                ('military_change', models.IntegerField(default=0)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solutions', to='main.probleminstance')),
            ],
        ),
    ]
