# Generated by Django 5.2.8 on 2026-04-29 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='probleminstance',
            name='budget_expiration_change',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='probleminstance',
            name='citizen_satisfaction_expiration_change',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='probleminstance',
            name='environment_expiration_change',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='probleminstance',
            name='military_expiration_change',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='region',
            name='problem_expiration_turn',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
