# Generated by Django 5.2.8 on 2026-04-22 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='budget',
            new_name='economy',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='military',
            new_name='military_power',
        ),
    ]
