# Generated by Django 5.2.8 on 2026-04-30 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_probleminstance_budget_expiration_change_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameuser',
            name='highest_round',
            field=models.IntegerField(default=0),
        ),
    ]
