# Generated by Django 5.2.8 on 2026-04-23 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_budget_game_economy_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='probleminstance',
            name='ideal_budget',
        ),
        migrations.RemoveField(
            model_name='probleminstance',
            name='ideal_citizen_satisfaction',
        ),
        migrations.RemoveField(
            model_name='probleminstance',
            name='ideal_environment',
        ),
        migrations.RemoveField(
            model_name='probleminstance',
            name='ideal_military',
        ),
        migrations.AddField(
            model_name='probleminstance',
            name='budget_tendency',
            field=models.IntegerField(choices=[(0, 'Downward'), (1, 'Upward')], default=0),
        ),
        migrations.AddField(
            model_name='probleminstance',
            name='citizen_satisfaction_tendency',
            field=models.IntegerField(choices=[(0, 'Downward'), (1, 'Upward')], default=0),
        ),
        migrations.AddField(
            model_name='probleminstance',
            name='environment_tendency',
            field=models.IntegerField(choices=[(0, 'Downward'), (1, 'Upward')], default=0),
        ),
        migrations.AddField(
            model_name='probleminstance',
            name='military_tendency',
            field=models.IntegerField(choices=[(0, 'Downward'), (1, 'Upward')], default=0),
        ),
        migrations.AddField(
            model_name='probleminstance',
            name='rarity',
            field=models.IntegerField(default=1),
        ),
    ]
