# Generated by Django 5.2.8 on 2025-11-20 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_game_player'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='game',
        ),
    ]
