# Generated by Django 5.2.8 on 2025-11-20 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_region_game'),
    ]

    operations = [
        migrations.CreateModel(
            name='NameRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='probleminstance',
            name='region',
        ),
        migrations.AddField(
            model_name='probleminstance',
            name='max_budget_to_appear',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='probleminstance',
            name='max_citizen_satisfaction_to_appear',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='probleminstance',
            name='max_environment_to_appear',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='probleminstance',
            name='max_military_to_appear',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='probleminstance',
            name='min_budget_to_appear',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='probleminstance',
            name='min_citizen_satisfaction_to_appear',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='probleminstance',
            name='min_environment_to_appear',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='probleminstance',
            name='min_military_to_appear',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='probleminstance',
            name='time_before_effect',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='probleminstance',
            name='time_before_expiration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='region',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='main.game'),
        ),
        migrations.AddField(
            model_name='region',
            name='problem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regions', to='main.probleminstance'),
        ),
        migrations.AlterField(
            model_name='probleminstance',
            name='created_at',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='probleminstance',
            name='possible_regions',
            field=models.ManyToManyField(related_name='possible_problems', to='main.nameregion'),
        ),
    ]
