# Generated by Django 5.2.8 on 2025-11-21 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_nameregion_remove_probleminstance_region_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='probleminstance',
            old_name='is_resolved',
            new_name='is_active',
        ),
        migrations.RemoveField(
            model_name='game',
            name='start_time',
        ),
    ]
