# Generated by Django 5.2.8 on 2025-11-22 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_is_resolved_probleminstance_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='probleminstance',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='probleminstance',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='probleminstance',
            name='time_before_effect',
        ),
        migrations.AddField(
            model_name='probleminstance',
            name='budget_bias',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='probleminstance',
            name='citizen_satisfaction_bias',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='probleminstance',
            name='environment_bias',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='probleminstance',
            name='ideal_budget',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='probleminstance',
            name='ideal_citizen_satisfaction',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='probleminstance',
            name='ideal_environment',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='probleminstance',
            name='ideal_military',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='probleminstance',
            name='military_bias',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='probleminstance',
            name='name',
            field=models.CharField(default='Placeholder problem', max_length=100),
        ),
        migrations.AddField(
            model_name='region',
            name='occupied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='solutionchoice',
            name='name',
            field=models.CharField(default='Placeholder solution', max_length=100),
        ),
        migrations.AddField(
            model_name='solutionchoice',
            name='time_before_effect',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='nameregion',
            name='name',
            field=models.CharField(default='Placeholder name region', max_length=100),
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(default='Placeholder region', max_length=100),
        ),
    ]
