# Generated by Django 5.2.8 on 2025-12-02 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_probleminstance_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='probleminstance',
            name='ideal_budget',
            field=models.IntegerField(default=500),
        ),
        migrations.AlterField(
            model_name='probleminstance',
            name='ideal_citizen_satisfaction',
            field=models.IntegerField(default=500),
        ),
        migrations.AlterField(
            model_name='probleminstance',
            name='ideal_environment',
            field=models.IntegerField(default=500),
        ),
        migrations.AlterField(
            model_name='probleminstance',
            name='ideal_military',
            field=models.IntegerField(default=500),
        ),
        migrations.AlterField(
            model_name='probleminstance',
            name='max_budget_to_appear',
            field=models.IntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='probleminstance',
            name='max_citizen_satisfaction_to_appear',
            field=models.IntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='probleminstance',
            name='max_environment_to_appear',
            field=models.IntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='probleminstance',
            name='max_military_to_appear',
            field=models.IntegerField(default=1000),
        ),
    ]
